//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autenticar
    {
        //rol de usuario en el sistema
        public string usuario { get; set; }

        //contraseña para el rol indicado
        public string contrasena { get; set; }

        //bandera indicando la sesion activa
        public Nullable<bool> flag { get; set; }
    }
}
