//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmpleadoDesarrollador
    {
        [Key]
        public string cedulaED { get; set; }
        public string nombreED { get; set; }
        public string apellido1ED { get; set; }
        public string apellido2ED { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public Nullable<byte> edad { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public Nullable<bool> disponibilidad { get; set; }
        public string direccionExacta { get; set; }
        public string distrito { get; set; }
        public string canton { get; set; }
        public string provincia { get; set; }
        public Nullable<bool> flg { get; set; }
    }
}
