//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Habilidades
    {
        public string cedulaEmpleadoPK_FK { get; set; }
        [Display(Name = "Habilidades")]
        public string conocimientos { get; set; }
    
        public virtual EmpleadoDesarrollador EmpleadoDesarrollador { get; set; }
        public List<Habilidades> listaHabilidades { get; set; }

        public Habilidades modeloHabilidades { get; set; }
    }
}
