//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Modulo
    {
        [Key]
        public string NombreProy { get; set; }
        public int Id { get; set; }
        public string Nombre { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
    }
}
