//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Modulo // porque partial? es por la relacion???
    {
        //Data notation 
        //Sirven para hacer validaciones o dar formato a las variables

        [Key] // Creo que se refiere a PK o FK
        [StringLength(15)] //Constraint que limita los strings 
        [Display(Name = "Nombre")]
        public string NombreProy { get; set; }

        [Display(Name = "Nombre")]
        public int Id { get; set; }
        [Required] //Constraint es necesario
        public string Nombre { get; set; }
    
         public virtual Proyecto Proyecto { get; set; } //FK?

    }
}
