//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Proyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proyecto()
        {
            this.Equipo = new HashSet<Equipo>();
            this.Modulo = new HashSet<Modulo>();
        }

        [Key]
        [Required(ErrorMessage = "El campo es requerido")]//Error si dejan este campo vacío
        public string nombre { get; set; } //metodo que regista y devuelve el ingreso del nombre

        [RegularExpression("^[0-9]*$", ErrorMessage = "Caracteres invalidos")]               //Valida que solo se ingresen números
        public Nullable<int> duracionEstimada { get; set; } //metodo que registra y devuelve la duración estimada
        [RegularExpression("^[0-9]*$", ErrorMessage = "Caracteres invalidos")]               //Valida que solo se ingresen números
        public Nullable<int> costoTrabajo { get; set; }// metodo que registra y devuelve el costo de trabajo


        [RegularExpression("^[0-9]*$", ErrorMessage = "Caracteres invalidos")]               //Valida que solo se ingresen números
        public Nullable<int> costoEstimado { get; set; }//metodo que registra y devuelve costo estimado


        [Required(ErrorMessage = "El campo es requerido")]//Error si dejan este campo vacío
        public string objetivo { get; set; } //metodo que registra y devuelve objetivo
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> fechaFinalizacion { get; set; }  //metodo que registra y devuelve fecha de finalización

        [Required(ErrorMessage = "El campo es requerido")]//Error si dejan este campo vacío
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> fechaInicio { get; set; } //metodo que registra y devuelve la fecha de inicio

        [Required(ErrorMessage = "El campo es requerido")]//Error si dejan este campo vacío
        [RegularExpression("^[0-9]*$", ErrorMessage = "Caracteres invalidos")]//Valida que solo sean números
        [StringLength(12, MinimumLength = 9, ErrorMessage = "La cédula debe estar entre un rango de 9 a 12 digitos")]//Valida tamaño
        public string cedulaCliente { get; set; } //metodo que registra y devuelve la cedula cliente


        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipo> Equipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Modulo> Modulo { get; set; }
    }
}
