//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class Proyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")] //Lo hace automatico, no se pra que sirve
        public Proyecto()
        {
            this.Modulo = new HashSet<Modulo>();
        }

        [Key]
        public string nombre { get; set; }
        public Nullable<int> duracionEstimada { get; set; }
        public Nullable<int> costoTrabajo { get; set; }
        public Nullable<int> costoEstimado { get; set; }
        public string objetivo { get; set; }
        public Nullable<System.DateTime> fechaFinalizacion { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public string cedulaCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Modulo> Modulo { get; set; }
    }
}
