//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Requerimiento
    {
        public string nombreProyecto_FK { get; set; }
        public int idModulo_FK { get; set; }
        public string nombre { get; set; }
        public string complejidad { get; set; }
        public int duracionEstimada { get; set; }
        public int duracionReal { get; set; }
        public string cedulaResponsable_FK { get; set; }
        public string estado { get; set; }
    
        public virtual EmpleadoDesarrollador EmpleadoDesarrollador { get; set; }
        public virtual Modulo Modulo { get; set; }
    }
}
